[Close #18] Updated README.md to follow up changes
pjhjohn/festime pull request #19
Opened 2016-09-19 07:06 UTC by pjhjohn

2016-09-19 10:56 UTC, prodia4 commented on README.md
> +    index.css
Should be `index.scss`

2016-09-19 11:00 UTC, prodia4 requested changes
순서를 이렇게 하는 것이 맞는것 같습니다.

`index.css`를 `index.scss`로 바꾸기만 하면 될 것 같습니다.

2016-09-19 15:24 UTC, pjhjohn commented on README.md
> +    index.css
수정하여 추가하였습니다. 마스터를 머지하여 Auto-Merging Availiable하게 만들었습니다.
덧붙여, `.css` => `.scss`로 변경되면서 알파벳 순서상 `.scss`가 `.js`보다 뒤에오는게 맞기 때문에 맞춰서 재배치하였으며, `src/`디렉토리의 파일구조는 `src/README.md`를 만들어 기술하였습니다.

2016-09-19 15:25 UTC, pjhjohn commented on README.md
> +    index.css
다시한번 보시고, 괜찮다고 판단되면 알려주세요. 제가 Merge하도록 하겠습니다.

2016-09-20 02:12 UTC, prodia4 approved these changes
Merge approved

2016-09-20 02:20 UTC, merged